name: Triple Bot 24/7

on:
  schedule:
    - cron: '0 */6 * * *' # Перезапуск каждые 6 часов
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-bots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install aiogram requests

      - name: Run All Bots
        run: |
          # 1. Запускаем основного бота в фоне
          python main.py & 
          
          # 2. Запускаем бота авторизации в фоне
          python auth.py & 
          
          # 3. Запускаем нового бота every.py (без &, чтобы процесс не завершался)
          python every.py
